k3s-token: ENC[AES256_GCM,data:ThuM5cf4VpYre0PaebiXnptzlHQba1qgVVQv4PJVzusT1+PAoktQ6HAvBzs=,iv:dYssaq/0Vs+jglFoT3qKpOm33wcRYzbosVu1g/yOVyk=,tag:o0zpEniJReN24x7+rUAp3A==,type:str]
sonarr-pg-password: ENC[AES256_GCM,data:GwZTy2eAGZ1FzwHc3+uuB59CcteG81KXUo2fe37I,iv:1LLS2xN6p1CYlCNqhuj5WT3JjKL8vnh8Lifv9R7mras=,tag:MVeinNGbtm5xXZL6n22fdw==,type:str]
prowlarr-pg-password: ENC[AES256_GCM,data:6ld4nMBayEmfBSprNwDczviqWlLEknI6Sh8iXhItqWI=,iv:7GW8xU4FDFDWfgIeM3TR3CqKia7WqiksFL47wjwPkqA=,tag:K/tpgO0I+MRptBlNcGGg6w==,type:str]
radarr-pg-password: ENC[AES256_GCM,data:Ntonl3pQDvxwZifJ62DSnrdJhCZlOqMkV6xd1TDJ/mw=,iv:6Ty8KfGeL4u3Y/ZjWU2RW5bEYSdfrwM0otyzT7Q2gJU=,tag:xF8lNAF33evTayYz8uEG5g==,type:str]
lidarr-pg-password: ENC[AES256_GCM,data:vhKbi+zb8VHMtvd+Ju0omXkUxjBrfLRRVlkolQ/nW58=,iv:RTDSBjQ3zRa0glyr/pCrJaQsStnrhzQQcT2SdAThsf4=,tag:nKyqBkTvNAWgopPbHjWHWg==,type:str]
cloudflare-api-token: ENC[AES256_GCM,data:q5plGTmUNKCIgJyLFC3prWURfp2/+h+QaUEoPhYfWPU5HsFg3+ecnsVfTooWSbn6kk2M0J8=,iv:XJlbfVG15+ShelsYO2rVwCpvuxZ65EM7n3H9KotlKWM=,tag:7M1eKmVFdB+mMSPWBg1ngQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMzcrdU1SMmwvSHcvYVRa
            VzZVQmJabzhvOS9hcDM2SzJ0K283QVVSNjJFCk1yTzBkRU9UOE5VZXdmQ3FtMVpX
            cFkyc2ZIcE9vbGY0TXFyVUVzK1FsdlkKLS0tIEhWaVpTOXJYbVB5ZDVwQk0rKzIx
            L1F6RnVnSTlsdERHb04wK0NMbFdha28KWRNfIaeuDegWqll33ZhzOkO1tjFfP/pb
            0gOfB2ZVineCPAr5Zbpjz4C+ZPqQ7S6goxz0xe+RlI0mPemW1iCoRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRTNVU2pHMjZlOVRtT1RP
            K3A3cEprSjBxL0Z6KzJPbU16TU5rYlBkVHpBCmNzcUkyZmpYcGJva3AzYkxVU004
            N09YOE16NGtwQ3JGZjJjYUxRYlp5MXMKLS0tIDYwdk9Nc3A2YjdDVW9LRERxMzlZ
            WVZIbnRrZTZIaWRIYTYzNm1uelRtVTgK0mRoB1lDx0i4lXOjJ0bRH26gVqbhrf2B
            Gi5FRgPtaGUJvQxEupmsScoQx1mL9d9ZeZOLzr5RMssNLzy8hQei4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QmNmR1dvUFZDNERXODFB
            RndGY0ZxNkJncERPWXdNTkZDWE1Ca1ZLYkJFCm5xd0lKbXpoRHoxbnNnVmE0N3hy
            ZE1tTytIQTlMamkvaS9zekhYTFVralEKLS0tIG1nSmZhZ0N0UFREL2YyQm80czgv
            VTVsNVIyc3hBWllDNTFYOWltOGFXeW8KFfxukxyVhdMQ6lQ5livgCxFSzv/GkGyz
            hs2uvZpZPAVCMlnHrocMztaH9IRi2iI1btiiedOPZZL3NEFormC+JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19z34wtc5mwhhuj2uw9vlsd4dw5frsc4xpx63qhh8s0l864k3338qv8agrp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYjRNblpBT3p6d2dTSlp4
            bTBaS3RNQkRMYUlnYUJtamxuK3IwcmE1amtFCklMS2pKeXBPZ1k0KzlLMXhKQi8z
            cEpHTGNabVhOSUFwcVFXaXNQSm1vancKLS0tIElvWURVZEcyU0tlMTlxUytWbXR6
            S3JjQzFySG44N213VGorVm1kQ05kR2MKs+pPHVw3m1zZX7+8Prp6IjxlfhrynYpD
            EDgbz0adIsYq1I0M4RjRSLR9mBnJ55sll6Lz98TNtjPEmi730fIKAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4yjlzh3w3jrpsq5agjg3ynrc77tujg5qkp3x4xj78r9acpryueq2d773d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnL0RidURDZ2xzNHpiQ2VM
            Q2l6Zy8vNnM4UnZMOVJvckNjS1FBU3VnZVZjCk8wRUx6Z2xiUTUxRjlpdXNJQTVC
            Z0JlZDdIdXhUckV2TWZSL2xaNXRSRnMKLS0tIDNnUEh2V0l1aVoxUnRFbkVndnN0
            TFlxQnVGeVh4N1hZREV0Z1ZURlpsWnMKW81yNW+GR2orxz+RauM0HhbPVDd7zQ71
            Wy+ebKtBLyn35QFjPTDRXvvnpoeMXZ/VTnYaTPAsstLnraJ+QpVw1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12cqnrpq4xml8hsf7yds5jkuknaxdsu55v0yn8tmaj8ayr4jsndxsev4nmu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaExRZFhVNEl6V2Z6QUl3
            ZWcxZHlkNzREcnl3Q1VnUURqemd3TGd1V2dVCjNaTWVFUGV1ZkFYbVR3WEpjV1BT
            WEJVR1dSNHQxbkRvdGxmdlNGMXMvbGcKLS0tIDc0TDgvZHZLVXZTOU02NVZlKy9S
            MkRQaWYvYU04Z2RvMWdURU9PQzhyYUEKZHC7NNNMb+2dwv0eULMDf/zbsLlt1WU8
            coCc8eOcIrul2U3cfWvQgRw4fPwC9XFClQexTMrAA/Z7+e9dheV8iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tyukq062khl7petdl5kzrzt4fhj7zxgpr7mdd2g0upvfr5cq0pjq5l623f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTDFXeTF5ZFlDRTk2K2V4
            UkZ5ZVUyQ3VVU0NSU0dnc0JQOXo2VGFodTBRCkg2QURSV0p1b1JRSE9yNlZTSHo5
            c0tNWW5oKzZ0akF0L3BoZElLSXZMMWsKLS0tIEV4dXNMZXRzUDB1SjBaMGZyWmo0
            NVo1RFdJdmZFUHdaSCt0cmxsY2tuUWsKd5dMkkPpoazYDgEWIofm/LwUHuItpRiN
            yBCQV3gfcMEb8ajbF3j8q493Sgi+r+vMiNF2Khp49io3XtNpvJV8cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3flzlc0rs48ynxhqvt7u8vwl4spmqzqvfclw4nmlf9dysnz9d4q5050lj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SUFhcG1vK3NueWFpR0Fz
            aXJmTkRJWnRmelJHaDltRDhjL2RtYTBKN2o4Ck1Xa3dyenpLV2k3c1BhNU9ZUmN0
            emlsOU9NQ25TZ3MyWU12blJHbHkyeG8KLS0tIFJpbnA3M0dHMmI4bE9BbTNlVEpj
            ejJsU0ZVZ1gxblBwc0J2emo1SUJpdmMKnmkBOuFk7WXh3TwkjMqnfMc7lFAtyeuj
            Xl2+KIcV9mHLkZvX+OrU1POmBJFlw0yU5mv21F3mhX+wI77l6M+bRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msns7ve6r7e89wwedxzyjrdcv4vvevuxna009j9ftxmkdhz8tfdsge9gh4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK3hDUlh1UmREYXA5dzRL
            NjlFb1NDTFRXa09IZ2V2ekoxbzV0MWs5TmkwCldLMW5xQVcxSTREeUtzZldETTNI
            N2NpVnVDOGpkQjBMckx0V1VMWFo3eWcKLS0tIHBlcEZWckhVdFovRTh5Sk12QVU3
            QnEzaS9wc3Iva1IwL0ZKWjNWTy9wWTAKXmiISEXQf9epXU6jv7YupIHSf3OknhIV
            n2apsJfCL+Vof4GzdSp1pq8uxXjj2JuL/Ed+zEBIUcf+VC1+xpcNJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lg0kagnvdn78gdshupm7aspekhfl9huxuetftp42hrgd9pkq6yfq7thptq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLc3VONU85NDFKMG84eHdL
            K0c0clRuZnAzQmNSRWRDazNiNW83MEpIeWdjCm0xRUx6S0RNNmt3ZEY5M0VPakFW
            N1BNUTcyTWpNUytSeHV6Q3A3ZHJGQzAKLS0tICs1WStvK2laU3JtNXh4OHBwUHdn
            UFNyV1pFdVorUjFJc09BZzI2a0Q0K2cKMxxbAmkTUzckPDjznhJQvs09x4YukHW3
            jl80kmXFIss0u3D7UmQae8b5/Y9Fq7+OaSDBJBN7110GmZ808GBW7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ljtnavedtk9jycwaancuq0dsuz0d9ys4mvv082r77qsvjfgq9snjhshc
    lastmodified: "2026-08-24T21:03:52Z"
    mac: ENC[AES256_GCM,data:W91fFBKlkrL1A0oppG2RHxhBf64EJheI+WGDQM7vxjn47GvobIABQ9ZSQQO4ZMlIuzB9yahDXnDHsa03+8kNghdSjgZz8kpEwkoJ/WouaybIZmGEKMEmQM/j7P2SVzsdPvJvZlSEY2URt//aD86wJ7es1YjuaDBBKZqAqdUDyKY=,iv:ttpTk1RJKI+9uqa5/8kWk7tp5QY0gHZEIf2brYgoEIw=,tag:Q1TLXl+8wHzSTVoCEr7pig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
