k3s-token: ENC[AES256_GCM,data:ThuM5cf4VpYre0PaebiXnptzlHQba1qgVVQv4PJVzusT1+PAoktQ6HAvBzs=,iv:dYssaq/0Vs+jglFoT3qKpOm33wcRYzbosVu1g/yOVyk=,tag:o0zpEniJReN24x7+rUAp3A==,type:str]
sonarr-pg-user: ENC[AES256_GCM,data:QhodG+Px,iv:/+8p/XL77DkaYg/VU5D9oBU4w7Z7hdO71Iy20ZkOV20=,tag:W2GWvYssto07vYxKFjnxTA==,type:str]
sonarr-pg-password: ENC[AES256_GCM,data:GwZTy2eAGZ1FzwHc3+uuB59CcteG81KXUo2fe37I,iv:1LLS2xN6p1CYlCNqhuj5WT3JjKL8vnh8Lifv9R7mras=,tag:MVeinNGbtm5xXZL6n22fdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VXFLdWd2QWtJTU10NGNm
            bFVQcDFhL0VpNmZReVBhNEttOU5pTTRRQjFFClNycXhTYWVwNXNKdjJxZ2JIWHRl
            a3gzQXY1Mk1pekJ5NzBDQ1o1VDluMU0KLS0tIE1ESjJPR0YxSnBKOXkrd1hRdnJG
            T1NEVlJaUEhNakV1b1hwYW9IbUdwNzQKW04ZhvazalCH2AD0eCuy+qfneJsICIXT
            Yhf5HRnFS+z9/M6UfH5pnX4EMSl7YIMZ1l6WyGLGvaJXi0/nh0KieQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUGZDR2F1Uncva282eGQy
            cGlLamloN2tpVFZ6RCttWEVBU20zWW5YelM4Ckk3YmVCM003b2wrbG9JSlgyNzFC
            NE9aUmdscElPMG9YYlBMcjA4dDJzbVEKLS0tIGk3aGJQODNrUElsR284SFo1bjNY
            blhZV0hpd2lIZnFEQlI2K21KWGJvbHcKMVZ20l7AXzJYkvD/JgGgSGFjspOmKHmE
            ViNacmgoaqqthCKxAgc84sr9wV0D8iRJ6/8tdAPYnMJqEQUhPPcQOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TndYQ1l5V1ZXODh6Rm8x
            SmdSbGowRmRoNytzOU1EQnNONXpFdTZvOUdjCkRoQlhIb1l4a3hkZnJjRDJhWWJ1
            UXRISnF1NFhVOFBqdkJNL0cvZ1RoRkkKLS0tIE43UWV3ZXNvMzE1SU1vZDN2ZXpK
            YWFpeGkxK1lZMGM4bUo2cUZWTlZ0RzAKPFqX1ETagP6pWKW+pGTGXUxwI5c+Jeuz
            7tdwvyP+axT5Qrr2yNeB4+YENPIBODdhj+7765s8PG6+eMpALqukdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19z34wtc5mwhhuj2uw9vlsd4dw5frsc4xpx63qhh8s0l864k3338qv8agrp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeDZQYklYS085TTF4czJz
            Uzg3L2ZQSzZkU0VTaHlEZWNRR3NtWXpkTjBJCjk4aEVZWWlxTUdSbXFmRFhWS1Rw
            ODZIVkZVUzRuMXpwTHYva2MxUnF4OU0KLS0tIDJjUHo2SFVTbmVDM05CUDc3aGE4
            VklMZFlJR2p2bFY4dVMzcVRvdGFCUEEKdEnOa3TZuIFOBfo2DyqLwkOK0qier86D
            H1kFGCC85rJARiF42ENUdR1hBHaqGVeg4Mr21VoNyqCFbYH/59cEww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tyukq062khl7petdl5kzrzt4fhj7zxgpr7mdd2g0upvfr5cq0pjq5l623f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdlFLVUNja2lGLzlJVEkz
            dVFpb2FqSE83SVorZlZhRkZQTk5RUHBPWVU4CmtXYlhlMjcyN1dSd0syZTJndUxq
            MDBHNE9FOURCbHpmRUsvWGN1S1V6TGMKLS0tIFZMenc0WGp1dFJWOG1lY2IrZDB2
            OXJFTFM2YkJIZisyZFVySWY3SlczeU0KWjL1DUr9upM6PAV9WiMnu3mH1qeUli+n
            KBafQud9byHDZOw3W24lRJhDYNhQ1MvCTuYvJDGAI9YVXfrDHlkmuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12cqnrpq4xml8hsf7yds5jkuknaxdsu55v0yn8tmaj8ayr4jsndxsev4nmu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Y1Z2NDBLMXBhNXJ6WUpj
            dmJ6TTFQUTY3ZFJjNHJDaVExZCtUNlErZjFrCnpIdkt2bE9EcFFRc0lqOVhTZUtZ
            UWowQ3c3cUZpUDBrM20vL29GcEREQ2MKLS0tIDFkckhlUEx0UU1rd0J2aWNoYnBY
            Q09iM2c2SVlpbGlOY2Nhd2NndnBZY00KPt4Hc8B3G94ngoLJEr+rm/phI2Xs7zBm
            tjY0+EKu+pYBSngV/pjpZ3cRfo+JzXEE8LG80Pqb8LX7KSzwdlJejg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4yjlzh3w3jrpsq5agjg3ynrc77tujg5qkp3x4xj78r9acpryueq2d773d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRmhnL3lSbEpyLzNVSmJT
            RXh1VmRCb2JwaWNzZHkybjlzM0xyRkgyTXhVCkxBN0FFVHB4RFVjOHBCSnBvVUNx
            ZUNZcHMzcXBmY1lQTEtHMlJvN2tCbjQKLS0tIFAvMVM1bTducWVCV2EwL090Sysy
            QXV0NFNhT1RrZm9tRVZiOFJ5aDlGMVUKNrnO7iAOWGZbTCc6MuDqQL86oKsNDa0C
            4mLEbUJqUyZMIoSr7QpUXtGh3dTM42amlgsGM/pf2rBClrfHzdZuRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3flzlc0rs48ynxhqvt7u8vwl4spmqzqvfclw4nmlf9dysnz9d4q5050lj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdFlnOGdxSUR4eFNVY2wy
            TEgvN3EzbUhlSnVZWTBCLzJKMjVyeWhDdVZJCmR3YW0wU0N5VGxWSzBhZ2doUWxw
            SkZUalUvUWJCekxrRllieUNsSWNYNnMKLS0tIG03TU91c2ZCL0JJK0JzV3hJU2gy
            b1ZXZy9La2JQK29PbENnZThuTUlFL3cKVyDMtciaWw22m4/lcXCOBVUGe3OwUf55
            W3bDxr9MHjbwyZyDkckl8zWnBDprJBT3jLO0SolOlGRirvURmZksJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lg0kagnvdn78gdshupm7aspekhfl9huxuetftp42hrgd9pkq6yfq7thptq
    lastmodified: "2026-08-21T21:01:25Z"
    mac: ENC[AES256_GCM,data:Oa1MgWOMFHRtqY9CFVjX1EQxYVAc0mL00XA8udTZgZ/85w1LkB+1edfKoSMgjAOthmtdSLBKsQloUodngbR9IGzuIfUnVth0qcXrnwcTBhM6WyCxL6N2robEMdn1u4nN/ompt/gg+sL9JRqKuA9SbsYcSIuQStrZPXCuBdWE8y0=,iv:8eQeYr0ZO8nHUI5+oRF7fh1fd4nytb1DQc9iqsRlD3c=,tag:MLI781b3ip/0i/nT0u3D3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
