apiVersion: ENC[AES256_GCM,data:OzQ=,iv:Dm18zmfMK+4zL665ZzO10lITWNIjWO8tWMMzfM+u2mU=,tag:SCJ4q6BuKtZVcWqbg/nHNg==,type:str]
kind: ENC[AES256_GCM,data:NfbMI+N2,iv:RTZnfmebnOyFjq89tFrqKT0kqI/cQxKSnriUdIZo0DI=,tag:C4Cj0zkkDCyY2vHI79ovUQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:K4ps6vHE7FqotGUV1UNEnLkraT2DZBDQoMKo2JI=,iv:xEe4CBNBYxe1nXrmIDwn9z8vrqHOONg6PHbgefZX4yU=,tag:PAB/e/VbmgeCIsKXiQayXg==,type:str]
    namespace: ENC[AES256_GCM,data:sopQTmPrczBX7Uw=,iv:1P6hQNO+YiqIK3kWY7P/ex3TwzQEhxXR4pQuMj/8AJs=,tag:YlcL1j6c2xF18XM+hm0hTA==,type:str]
type: ENC[AES256_GCM,data:bpW9aMay,iv:e7QHrJw+nPWpL/vXe7G9Ey64GZ5ES5+nS6xz/+6Szy8=,tag:p5usmUtSUXDg5WDhTu2mJg==,type:str]
stringData:
    nfs-subdir-external-provisioner: ENC[AES256_GCM,data:wetBgm21WY22Jmmh/sHgt5H0oFKFUY11U2xFPh4eK8n14gGf/dwBqP4+0pa/T0UvVCOEnUkcjtut,iv:rXvOOtrTfxiwZeH8GF3MYncf8v6aNYIWL4IVfRnxRXc=,tag:nBRZeYBtHbop1OCLdVbKAA==,type:str]
sops:
    age:
        - recipient: age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NnF3ZGZnSnZTelVYSGs2
            R3AvM0RZODFabXQreXNZK2xRTmk2VHZtMGhJCkJWbFJhWnQrazhSV2NITThYRFBn
            Q1dQZUFFSXZkc3R5bHRpYlZYRkdMNUUKLS0tIENpMExFdGsyZ3pVV0RvZkpHS3lN
            MkxaQVdma20vNFlDRnRsWGFvUkRqNUEKVG49AYBPMLctD9nCwon2xr31ZexYcX8q
            zLJg+fRUwVHM2cKhxVkRk65ewsA2Vn+skdA53udFqWyu7bX+lWH7xQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ3FiRHJ3OVo5WUZ3cDJS
            V1BMaFZkQUlYWXNhbzg0L2pFZ2JkNzB5QkRRCjM0VWhWaEtQK2dLYk1ySlA1dVZ3
            dkhtTkUvOCtsTTV0SmxzOE9YZ0lMWGcKLS0tIG5NbWlVdVBtUkp0cFpvZko4SUxx
            bmlCV1YzeTNteCt5bnl4QUtwYTJRa0UKK4nISxo8/2f6j8d7I3mmUcxbVSNwKQb6
            3bAS9aWwQY9loS4o/rb420gHFgxW1HiQ5rJP9p6/ChjxlwA5pPcBZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e54sda30ksfjdjkrqsqvc252k3nc6unlk5len9pgyvmwkl20yggszwa9g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K0NnR1JNRG9BMkNnWG5C
            OUNxRnFkOFN6N3pBcTZ5algxUWt4R1UwMTBZCjczcitqL2cyRHF5QWh2Ui9uS2RS
            MEF4TEZ6UWJHTW9sbXQ1L3NGLytuTEEKLS0tIFdoalpXZ1NnT3RKQjIvdlRiWDhY
            eno3T3RVdWJOQ21LUjF5ZGIwaFovZE0KfKmMVI13Xs4a2qwlrmfkwDNpED2FdGYq
            MNsxvDkcHrQh5CWDlOlnlOBd37FhgLtqy2apwbzBanA9+k5mhyiFwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uth3uygu85kqwvfdwht6n3q6a3zzau0sje9s0ueegc28hts64lqlazz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTWNyeEYzamxHUGE4c0dD
            T3E4WXUxU1pab3E5bFk4WWZxekpIU3NZSGtrCmpUMVZwSDRVbWp4TUtTZWhTM1Bw
            UldaTStUcTZHUHdHekhLaFRZRWRJZ0EKLS0tIFoyVitqczE5Tm5kZ3ViT3pyQVk4
            bElaY2dwUGhYWHh3QkhBYW1hM0VBWDgK4N48E43VA23cE+A1ZJOmarNuUnOF1dB9
            /o6thQ9NSnN2s03w9SB4SbaVYz0nYrbBtAbt9yqlfGSL/vBUulN6fQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w56kcwe2ec078ldf0yr9langknelkc29wlss5tpve2lg5hdfp3xq55xh84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eWF5cHJuOVFEZzdZUTNP
            ZU1LbGV2TkkyaCtIQzdrdksvQlBjNUg0NUZzCjF6emxlWTFVWTJwVDZFSGNyTUlj
            U1dSWEpOczErU1ZZVEdFZ3I0UHpicjgKLS0tIGRSWng4UTFhRCtsVnhUTmlyQllu
            amR0UUlWNEpLeGNNZmJBZGo0T3pmd28KyTSOMr6n4GivYhTWrlM7nS0Hg6dWjgIr
            F7pFdmjke2dyd18UzFTKC9XFRnujm5o0X0BdwxHRwsEOkBaM2bkw8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m3flzlc0rs48ynxhqvt7u8vwl4spmqzqvfclw4nmlf9dysnz9d4q5050lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1ZBWUl0ZzF1T1RCQWRH
            STlzNXd5cS91U1BGS0MrOStVUERZMGMrK1NFCkgwMms3d2pKTlJCd2dKa3dnNUhm
            d09McERyd2VpVVpTMzM2bmhwb29uUEEKLS0tIEk3eFg3bC83Y0FVdit4NEVTRzRp
            OXJTVWU3NU1INndCbUFSejNwK3ZwVEEKuBPoXuu4fGMxelKjKjHoyQcMljfjhNbG
            Ls9k6UXCTjeCyNnHPe5OkPylWw7ust2u0z3NYiHal/Gsa1zctZeV7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T11:30:03Z"
    mac: ENC[AES256_GCM,data:KM/GgcJ8Mhgxxihvywu7y1nogv8C44YU1alB7JTmm/NoW0n+IB6lj7OtstJ8UR1eqs1p4So9R46pR2DqRywTI8J4CDYpUufo5rfwlS5YENHuCUStDtvyeKc+SHRnA9K/TwQaM/T/TEYYqjlPnbWu9+bhkD4mZhXGOIyxDU4xdWo=,iv:1d97xFrUj+ypRUFy2dt71T3GAEnzwg4NaPElQUHkQj4=,tag:9yazv3KSgCrwGBH/CwYp7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
