creation_rules:
  - path_regex: terraform/.*\.sops\.(yaml|yml|json|tfvars)$
    age: age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w,age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd
  - path_regex: nixos/secrets.yaml$
    age: age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w,age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd,age19z34wtc5mwhhuj2uw9vlsd4dw5frsc4xpx63qhh8s0l864k3338qv8agrp,age1v4yjlzh3w3jrpsq5agjg3ynrc77tujg5qkp3x4xj78r9acpryueq2d773d,age12cqnrpq4xml8hsf7yds5jkuknaxdsu55v0yn8tmaj8ayr4jsndxsev4nmu

