apiVersion: ENC[AES256_GCM,data:Hh8=,iv:CuWZdfhDP6VlftxxTmCgY+0d5xCtoNgkY37XLc8WT8g=,tag:qrjbfDntxFvYv8CUmZff1Q==,type:str]
kind: ENC[AES256_GCM,data:QOu5zBnS,iv:gg4XnbLKR+EU5ixuTnFTTq4RaerywVON+Gef5y6Asj8=,tag:k/zkFAd81YE5KqJHtQ9PDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2GRMjGNfh98f2CDJbPI=,iv:B34I46FKPQzDJMuGIX2m4PerZzjMt03dmoigOO2IwC4=,tag:2i+HStV/AbiB7TWbYKVLmA==,type:str]
    namespace: ENC[AES256_GCM,data:ZYbZ0Sc=,iv:CQHS5N3tSLxMaOvUfJ4ySPNAxX7bMY5YYdGeRTwRFTs=,tag:6/PKLbp0NEAqDtMk0OVTeg==,type:str]
type: ENC[AES256_GCM,data:mN18mgrj,iv:C/kFb9yTe4qDINt+XCUM2PnxBXUnpv2qoxY35BtiOG0=,tag:72AXgdmVfuKzgedfXFE91g==,type:str]
stringData:
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:BlFCwUFebqSGLWe/cXhUAg8NwpMqFgLPVbEghvNU,iv:7V7GsGH+rrPZnNe/ysanpeBs+xcZ72v7loFECytnar4=,tag:sQk+R7Xao+/Mexw57FgnOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabjRpVEdpMnNYQWxqWmNp
            T3Jadngvanl0dVFUamZBZThoVWtTMXBEbFhNCnBFQzJCMmZkVXE1NldhemhmWk0z
            dnlwUkg4RENJT1ZHSUJ3dTFqQkQyQ2MKLS0tIDZBK0k0cWZiL2tNQ2RRVWlkRSs1
            dm54WktaaU5TSlVaN0FzUHdhT0pJMkkKCAFDEIuiAfag+yfSx5BxQcuiXVwdQiWh
            CYfK8/BlQjFT0h2soKSBfND4gX3hgVgPyb/vCIyjzQeeakm+YqMrlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVFdjN1UyQjdSTXlxYUxi
            cUppQnFTYXYwRGxRcGpVQnJTY3lLS1lhK0I4CmY1Z1g0elRwTWQwcGdnUythR2JD
            MkxpejFFOUIzejR6c0wrNWozZ1lmbU0KLS0tIHJiNmRFWDNRYmNvWnlWays1YThE
            VFR3YjdmQmhhTS9IbmhKS1A0TUxiL1kKex3trY8ZMFuA0JgXLQktcFe3KCFVRVgd
            SIGh6gLIiH25ChWal2FoUN1WQhZKGH3Xj/SUdlFUVRNlj5x1z4juEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TXpoVnRYRTJKaVA3Z28z
            d1dXSmJxeFpsZ3A3N3FzZFFyMXNVNjA3dlIwCm1JWEEvbVYzLzJmK2xhS2k2TDZa
            bEZRUXBBaG92TzBhWStJQXRBVDY5dkUKLS0tIDE0VHB1c2pYampMVWNtNDZNNU5K
            Wmd3bXBwN2F2V251enA4UEtZamI0YWsK7YX7pefGCm7P5n8p7YMqSo4gyzWJrqCm
            JM4/SxeJebE1rJLngciPQL9vkXIjvnjcNvb8yfI9ufDLMYyR2Yw04g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e54sda30ksfjdjkrqsqvc252k3nc6unlk5len9pgyvmwkl20yggszwa9g6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUklhdmQ0OHExM2wxWURY
            alRhYjQ4WkYrelh4bFZDVnBLUGRBREJ5eWwwCmFpeFNPdlJ5a3dIdzZ6SjZEM0ow
            MDZqVmRvWTRJeFhhUFJkZXF3emdVMlkKLS0tIE9WRXZjNDE3WFkvV2xwZEVJazUy
            K3RWcDR1YW1ibythWHhaS21laGQ2YkEKxCuHaQEzxNVynv9DQo3Lc1MQU0NI7SSp
            IuVz/onqx7WILsCBtcn4Rbo08Yuyy6fiPscWui6mO70VhaZlujkNag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18uth3uygu85kqwvfdwht6n3q6a3zzau0sje9s0ueegc28hts64lqlazz4d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVDlQc21ZSld0WnRtSm5n
            VUszUlZ2TXNlN3htbUlZRTVGakFWR0tsL0RjCkZVR0oyRWVyU2dObUxXdU4ybzVW
            QWFyRnRBQ0ZBWE9FSG9xSXZ3N2VXUlEKLS0tIDV0YlErZkNoOUx0dHVKUUg1UjRN
            ZUR0RGJCVFpNT3FkMkExSG51T3ljaDgKnp6YGEeVH6jYbuEJ+otwF9xMvJba0wbp
            ojdWEQKufv7QSA2KEBxDv+zzgJzdskny/5dNcrMmD6scz5z60qXJBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w56kcwe2ec078ldf0yr9langknelkc29wlss5tpve2lg5hdfp3xq55xh84
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMEdRbTBqMmJnWmFBVlRu
            NzE1a2ZpZ0FJZXFLTkxFMksxanRKQUxPTzBFCjlDL0prVFlUNDg5YXY0dG1oSkY2
            eWpZQlB1WENQSVFWRkNvUldWS3FscDgKLS0tIFRUSzVpVVVST1J0TWhqRG9QTnE2
            bEVucFlybUVSQlcxcExHNU9lUlE4MEUK8bzizzCqGl4XwqhGVmbjoGOY4cCtZfgR
            pdomnBb5k7DzLCxPpL4idkOGo/7m8ktxW+UAU8SJt3lvBr4yW6pI/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3flzlc0rs48ynxhqvt7u8vwl4spmqzqvfclw4nmlf9dysnz9d4q5050lj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKODRZYXdaSUtySDBWMUt0
            ajgwczQvTmRKMzV5V2RudzZKL3NiSUFVTzJjCmtyMzRVWjVGVUtBOU1kZU12TGVZ
            TmFWV2ladTFtVThkNVNUMy90TUVNVFUKLS0tIFFIWTlOd2lkT3JpeTNLeTJpdXV6
            eEFKMTJkZVE5TlV0ejJTOUdPUHVkeDQKDmzqRZAuo0YkgrFh/pr9SQlsOFIsge5w
            zU7kTFeco25+v/RNeDrOg9w4JlhmtBcQxgbkzjeVj+iLTGh0RXsqWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msns7ve6r7e89wwedxzyjrdcv4vvevuxna009j9ftxmkdhz8tfdsge9gh4
    lastmodified: "2026-08-22T13:55:16Z"
    mac: ENC[AES256_GCM,data:H1vzak/cC9JGjtlqrkIt7tmiqoyn3ZCFFsXzf89ubRU4A2zTotLBul74k9daOSVmy+4atkBuhDW3yNAQCtA+TblqadTaJa/GxhLCR7pP5xZEWvD6IVu/7gw7WBnKFU4Uqp48s1E/ETPmZG9KzvOjzjxr2biHkLXo1YUJLUlDltc=,iv:vKggao82HUE1HIXM7r4eBPimucJZZFShn3aXc6exR68=,tag:Lrbc55IVVmqHGqClqQGrBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
