resource "random_password" "authentik" {
  length           = 16
  special          = true
  override_special = "_%@"
}

resource "postgresql_database" "authentik" {
  name = "authentik"
}

resource "postgresql_role" "authentik" {
  name     = "authentik"
  password = random_password.authentik.result
  login    = true
}

resource "postgresql_grant" "authentik" {
  database    = postgresql_database.authentik.name
  object_type = "database"
  role        = postgresql_role.authentik.name
  privileges  = ["ALL"]
}

output "authentik_db_password" {
  value       = random_password.authentik.result
  sensitive   = true
  description = "The autogenerated password for the authentik database user."
}
