image:
  tag: 2023.7.2

env:
  TZ: Europe/Rome

service:
  main:
    type: LoadBalancer

persistence:
  config:
    enabled: true
    mountPath: /data/homeassist
    retain: true
    size: 5Gi
    storageClass: nfs

