image:
  tag: 2023.12.1

env:
  TZ: Europe/Rome

persistence:
  config:
    enabled: true
    mountPath: /config
    retain: true
    size: 5Gi
    storageClass: nfs

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
securityContext:
  privileged: true