apiVersion: batch/v1
kind: CronJob
metadata:
  name: symlink-to-local-downloader
  namespace: media
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: downloader
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - |
                  apk add --no-cache bash findutils > /dev/null 2>&1
                  /bin/bash /scripts/download_and_swap.sh
              volumeMounts:
                - name: script-vol
                  mountPath: /scripts
                - name: nfs-media
                  mountPath: /mnt/tower/data
          volumes:
            - name: script-vol
              configMap:
                name: symlink-downloader-script
                defaultMode: 0755
            - name: nfs-media
              persistentVolumeClaim:
                claimName: nfs-data-pvc