apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jellyfin
  namespace: kube-system
spec:
  bootstrap: false
  chart: app-template
  repo: https://bjw-s-labs.github.io/helm-charts
  version: "5.1.0"
  targetNamespace: media
  valuesContent: |-
    controllers:
      jellyfin:
        type: deployment
        replicas: 1
        containers:
          jellyfin:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.11
    service:
      jellyfin:
        controller: jellyfin
        type: ClusterIP
        ports:
          http:
            port: 8096
            protocol: HTTP
            primary: true
    ingress:
      jellyfin:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host jellyfin.k3s.middleearth.cc
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: jellyfin
                  port: http
        tls:
          - secretName: jellyfin-tls
            hosts:
              - *host
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteMany
        retain: true
        size: 200Mi
        storageClass: nfs-client
        suffix: config
        globalMounts:
          - path: /srv/jellyfin/config
      data:
        type: persistentVolumeClaim
        existingClaim: nfs-data-pvc
        globalMounts:
          - path: /mnt/tower/data
      cache:
        type: emptyDir
        globalMounts:
          - path: /srv/jellyfin/cache
