creation_rules:
  - path_regex: ^helm/charts/.*/secrets\.enc\.yaml$
    age: >-
      age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w,
      age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd,
      age1e54sda30ksfjdjkrqsqvc252k3nc6unlk5len9pgyvmwkl20yggszwa9g6,
      age18uth3uygu85kqwvfdwht6n3q6a3zzau0sje9s0ueegc28hts64lqlazz4d,
      age1w56kcwe2ec078ldf0yr9langknelkc29wlss5tpve2lg5hdfp3xq55xh84
