apiVersion: ENC[AES256_GCM,data:UCQ=,iv:pLAfYiV4jN+Mk7zaDkVumf3GqkskzU03j7pMQXW5PNg=,tag:Vn2UOY9oEX4a8ko8/2wGLw==,type:str]
kind: ENC[AES256_GCM,data:l4uAgPO/,iv:zpT2Y1dTm3f95rXYgS/61XKviSTlgbIPxqRmpzVU2JI=,tag:SoIgF4HSQ53QfTyfRxIpRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uB6/olm1/B3OsuXrEGlmjgYwrWBbQG35DZyM,iv:Up+HHR2nE7Czek+ClCCLKM78C08oIEHrZm2SKsHpsus=,tag:PweHgUP1uwlEDsh4kWslaw==,type:str]
    namespace: ENC[AES256_GCM,data:CufLXr2a+zMxOe1u,iv:3A7Q8KU4LmyvplneF7n4DBVwlzzlEP0oiA+H/7IZMcQ=,tag:C1i5AvvTc+Jrtgluy+gdxA==,type:str]
type: ENC[AES256_GCM,data:BsCNOUkn,iv:OS0hiHg/CEOo2/6nmLWfgl0syRL+Xq3hlrUdAcGPOqo=,tag:PFqVv8Kt0dyExEr68M5v8A==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:sxKMg+qUYxann7fBan91e/puMAab7bWcrl0KifbgTa3t0S8IfO0zcByE99QXdYsf28PJUC8=,iv:A3zo6esSnwtY5HWiqCdQhtVd6IIcUtOKX7zxOnSJkXw=,tag:0Ui/frLn3yV11IfLb/JEFg==,type:str]
sops:
    age:
        - recipient: age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRFRheUVRbmxPQUhVckZ0
            ZmZZOEF0Z0NOZ0E1QkdJa2t1VEtVREhUSUhrCnRCWWRhZ3QzNnF3OCs3dHp0alpV
            NnZlZ09PbkV5R3cvVkFLckNsN3c3NDQKLS0tIG5Jd1IzV2Q0NDF1T2VmcG9ldEpx
            K3Y5c1Uxby9QTk5MbGRvWEYzNDRLeGcKwhaAoUPmzFbKEiciN6xH+YKIWPH+r7a1
            uPYYsk4NmItFQhNNPYko1543OamNN6U36M4uz1guDvDddLYwuWeanA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeTVFTUNxVDRndHVSenhx
            NkVZUG5MQU42bnBqNzdoZGRWME5oeDhtUndBCmIwb0pZUC9SVVFTM0FYeGFTV0xh
            Z2pGUnBTbFN1SFZNbG0vVzF0L1o5azgKLS0tIFFwOGJtdmJKSnp4bWlYaVF4Rmdu
            MXlRSnZjZDVqVTJCQUJ2SGlQYm1LYUkKOcHzio1pgaZyZTiiut0qAeDtlGRjrZaj
            +05qkvO3qy0fBUA4zdONBFfrXVqWJay7gE3l2EwVka97N8hy8/1Dzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e54sda30ksfjdjkrqsqvc252k3nc6unlk5len9pgyvmwkl20yggszwa9g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZytiY0dIZWpMVW5Qb2JX
            S1c1T0pOODY4cHNoeUVhRHNtNFduVmlGaldBCmJweHF6SnIrNDVHMEo2Skt5VGhH
            eEJaWWJwbFVDRncyYmNMdHpWWnpmN2sKLS0tIDg2QldQMThoMCtxbmpmVUVoU2Mz
            U1VRVzlWWWNMRGk2V292eitXckJHeWMKK4B7LShQy77iK05AN104X4Xzqx6AhW3d
            5CB7QIC2rgI/Rg2zfo0sBM9v0H8YtWcHNDW0Z0DwguHA+aT7LmiurA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uth3uygu85kqwvfdwht6n3q6a3zzau0sje9s0ueegc28hts64lqlazz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRW1XTXlMQkhVb1liTHd6
            WHpOYUlaUWNNeE1PWk1MeEVJa3NQelNDcjMwCnlJSllxR2xOYWREWkVKOXQwdVNY
            d0lhczYycVp2N1A1YlBmd2t4RmV2c0EKLS0tIGJWUk9oV0VKRERoN1Izb2VmQWhT
            YXpVbTNGUFBNMEdjbDQrbFN5WHc4STQKQJxTrL6gSNcByZGULn74Pb09uTYsdiWU
            NyoTxO9SF2GQEVEZSDkHT3a+DWToIVP/83pusOVzUIUBWItwUJRGpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w56kcwe2ec078ldf0yr9langknelkc29wlss5tpve2lg5hdfp3xq55xh84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMEN3d3FKaEJBNGxsT2N0
            N0NZcE94NVVCb3c1Z0NyK1NWNU9jTmNST1FRCkpPNWZMUHRla0wrVEV5cklaMjRS
            KzZPY0NGTHUzMmZpcDBzRlkzY1VjVjAKLS0tIEtSSUw4b2E3VmZHektmUVpoTlY5
            cDUwWGx3bllrdkUzUUxMalE0TE1UYmsKDLLtajDSFBj+qO7VfvxjLhmFvjF5xLH9
            lshNwGCPVa2pnXxw2750AA/QS8sROyRUFgXMjthc4ZdPm9KB3k1GkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T21:33:04Z"
    mac: ENC[AES256_GCM,data:ECiQNKsD9uhq805x0j7IvxSKTtJUMI8TJsyjaqh1ThCkWwvv7RQcY4GyebBV18v260/qU+pAzL54BUBhsgJOZWqZ+Ot+iI9nSgZGen1LcsTcDVQbv3al6Hk6F/hKQ4Px1VqrO9ZqfWjLf6ODJUocU7rBcJPmubMvTgm+cna67qU=,iv:HmrEKi9gAjOvofHFKYAfWyQJwbekwNk+Y62/FAJPx78=,tag:Az/pjQLLxHJZ40kUttVr0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
