apiVersion: ENC[AES256_GCM,data:O+Q=,iv:cSx+di+SvJTIoCUB9fo51S7+RD9P7Si85b/0TL9CuLw=,tag:89PjJMqAhblkt7o34DEfBg==,type:str]
kind: ENC[AES256_GCM,data:UIuMpKpb,iv:PeNB6bJyIzaI3ufNvLyFbf6sdPUl7Y+FQUYqJv5smTI=,tag:GrF6ZKXNq+3FMdPsA36IUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YjI7XWVzvE/G7NLi9heNHfN9+D/VHdLNagSd4nw=,iv:pdnBJpbtxGE8zhbWL+cE9R9rlQ9HvncqOEaZ9Vamd1A=,tag:Pa3hgSoIQlTctVizSh4Y+A==,type:str]
    namespace: ENC[AES256_GCM,data:T1L/fzAFTr4hTzsp+MP1UF7jpjqj,iv:AZL21nUwTQ2XfVOpoKgLF64NO39HAbOJHOTyO3VuhJQ=,tag:UcL+th1nYO2OuTW5yDxFMQ==,type:str]
type: ENC[AES256_GCM,data:wq/x5Y6f,iv:J6TH1sDrhRWJ0XGWRgAzWEXEtABWtHOIvOaRUffhExY=,tag:PQYVB1mBLOtZVxvLp4hp6Q==,type:str]
stringData:
    bot-token: ENC[AES256_GCM,data:7yO8bwUZTQ1J6o88Egjm/dPXfxza+YS1nzkwnn1mIwGfRuSpD2NTo/rBVM8Dfw==,iv:m17bR2w3rAz31R8JvGo/FLQ+VkHS1m6DpZPWy5f9iRM=,tag:nVh2CXiZCdlf9csnMACoOw==,type:str]
sops:
    age:
        - recipient: age1s9pcy5q47g2jumr5xkl9arh7n6g9dl89h6apepe6nkkhfp7l64tqw7ey9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSm1OYjhLWnRYVHJsRm96
            QlhsbkpZMFdiQkVQVUEzN3ZsZU9HRHJXUHdBClpxczBvMFZ1K2g3MEE2aWNSNXRu
            QnowVEVZK3NUVFI3TWY2OXRwNWZhc0kKLS0tIDg0NmoxTk5BaGRRTFRLclNrbkJo
            Y3hUa3RSdE1xN0MvSVFUUnp4WmgxRFUKn6pz2w5Drm3NUJ035T12ErGzLabWmdVy
            JwkRQfUsLi4K7wXViT2gGMy/0WNDcu8ilxaSigxwTReUV4RLsx+kSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyyn5uru98vnct76c5dvkm9ctgs7a5a9r0lvg36z8t6maxklud7scy5njd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU0ZpYVVkMEQ1SlAxR2Nr
            aHVPd1lYangyTzVqLzl0QWtrb09xVUNHK3kwCmZIK3BOdC9rdDZLM3RkU3U5N3JB
            cW5jeFdDUkNZVUd4VlpjYSs0QmZhQk0KLS0tIHA0dENXTWMyM0ZqTDFacWZ0dCtv
            Skt3VG43OWNKUjlEQXhiWVlscXM4SlEK/XFZRrEgsvh5AsVHg6ocN/kgcJx2b20g
            yBNT0mbk+diL5u8iZFV7Gbzn5r5KceFKT/lQdGf3U9yvFS/vzpP1Gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e54sda30ksfjdjkrqsqvc252k3nc6unlk5len9pgyvmwkl20yggszwa9g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVklSNWFBbDNMbnZzR3p0
            QW5SanQwOHczQnJxb3FjSk5JU25PSlRNeWpnCkg4SklsU3dxeFpxYzZUNWlwOXZx
            RnZBTWpZRGVrQ3Uxb1pCaWtpSHVDNDAKLS0tIFBMa3cwRXlqdlROQzZ5YmJ1N0Zz
            OVlxb3Q2NnlxY1o1cTBCSDJZd0RzSTgKk0FfVA7L/GkLb4pEjGGH1l22bXyYAqEQ
            Q0bWR9h+jntNuy8BowKgH1VmOA+evQOCcOzO980MAPM5ECP7KB9twQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uth3uygu85kqwvfdwht6n3q6a3zzau0sje9s0ueegc28hts64lqlazz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcGZjbHV6T0dJakRUNzlj
            blFkbWVFUVJ5QXUyTmpvQjFtMkU2dlIxbkh3CkxucGh3U1FRQm93NTdYQlBGT1lh
            Z3hTNmlqNVF1L3ZHdW9PanU3NEM5cDgKLS0tIE5FMVVObUFNQkNOUk05QUkwOHMy
            T0hqOHl2OGk3S3ZuMzJJYzcwajNOd0UK1xxi0bNJ0mJAAZbXya1/+CohjYYSIUpy
            DAsH2EG5rA7YO0TeI40RofPKko4WZkluTfV2b3n4WscEaigghzLacQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w56kcwe2ec078ldf0yr9langknelkc29wlss5tpve2lg5hdfp3xq55xh84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dDRvVEttUmphOHhmZHJi
            d1FIYU9kWUtHK0RuSWh4cE03Q3pEeXp6WlJFCnRuNVlCdEdWOGxROXJSVWVkUHg0
            TlJ6RCtIMGhTN3UvdGQwQTBvaHY2T1EKLS0tIGhUbXdnbVlHNjA3SDUxRjlTcDNL
            MmRGUjFlSGdtQUs1NG54OXlodk1LQ00Kl7rtmsO/VA0cmFSZ/pAYj4BnkwTPw9Fe
            LSbIzCb5liDtyMkVSN0LPyExcRLMPkod+bUSrmU0wS3Cs6aOz+Rspg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:43:37Z"
    mac: ENC[AES256_GCM,data:cevbEHtRt9JjMz6GivG7MfvJe0PLqEHh6lba6QF77CRPObAvNCKsOFpm+5ARCpYC3fkpVkcr7cjFCsCJNZ1Tt4ZA/81oOHjhPDv+wlQroCm4443Uke06fsQnRaSV/3hgDHtLeHPG08cEa0sev6Xyrx11Puk4QkbX+6pr0zA9v8g=,iv:OCfceUs4ehkPRqzpF5Adc1l+7GV1mKzl4Idx2zbVfes=,tag:q4tKX7sWmLSK0HqS0lkpww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
